dist: xenial
language: cpp 
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T bulk-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uivan-krivosheev:$BINTRAY_API_KEY "https://api.bintray.com/content/ivan-krivosheev/otus-cpp/bulk/$TRAVIS_BUILD_NUMBER/bulk-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1" 
